[package]
name = "sql_printer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oracle = { version = "0.5", features = ["chrono"] }
dotenv = "0.15.0"
clap="4.1.4"
